# $FreeBSD$

PORTNAME=	ros-rospkg
DISTVERSION=	1.1.4
CATEGORIES=	devel

MAINTAINER=	trentonw@ifi.uio.no
COMMENT=	rospkg Python library for ROS

LICENSE=	BSD3CLAUSE

WWW=	http://wiki.ros.org/rospkg
USES=	python
USE_PYHTON=	distutils autoplist
USE_GITHUB=	yes
GH_ACCOUNT=	ros-infrastructure
GH_PROJECT=	rospkg
GH_TAGNAME=	1.1.4

.include <bsd.port.mk>
