# Created by: Trenton Schulz <trentonw@ifi.uio.no>
# $FreeBSD$

PORTNAME=	zotero
PORTVERSION=	5.0.28
CATEGORIES=	print

MAINTAINER=	trentonw@ifi.uio.no
COMMENT=	Tool to collect, organize, cite, and share your research sources.

LICENSE=	AGPLv3

WWW=	https://www.zotero.org
USE_GITHUB=	YES
GH_ACCOUNT=	zotero:build,standalonebuild
GH_PROJECT=	zotero-build:build zotero-standalone-build:standalonebuild
GH_TAGNAME=	b330e8e:build 5.0.26:standalonebuild

USE_FIREFOX_BUILD=	52

.include <bsd.port.mk>
