# $FreeBSD$

PORTNAME=	ros-rosdep
DISTVERSION=	0.11.8
CATEGORIES=	devel
PKGNAMEPREFIX=	${PY_FLAVOR}-

MAINTAINER=	trueos@norwegianrockcat.com
COMMENT=	Multi-package manager system dependency tool for ROS

LICENSE=	BSD3CLAUSE

USES= 	python

USE_PYTHON=	autoplist distutils

USE_GITHUB=	yes
GH_ACCOUNT=	ros-infrastructure
GH_PROJECT=	rosdep

.include <bsd.port.mk>
