# $FreeBSD$

PORTNAME=	kqtquickcharts
DISTVERSIONPREFIX= v
DISTVERSION=	19.11.90
CATEGORIES=	graphics

MAINTAINER=	trueos@norwegianrockcat.com
COMMENT=	QtQuick plugin to render beautiful and interactive charts

LICENSE=	LGPL21+
LICENSE_FILE=	${WRKSRC}/COPYING

USES=	cmake kde:5 qt:5
USE_KDE= ecm
USE_QT= network declarative gui core

USE_GITHUB=	yes
GH_ACCOUNT=	KDE
GH_PROJECT=	kqtquickcharts

.include <bsd.port.mk>
