# $FreeBSD$

PORTNAME=	ros-console_bridge
DISTVERSION=	0.4.0
MAINTAINER=	trentonw@ifi.uio.no
COMMENT=	A ROS-independent package for logging that seamlessly pipes into rosconsole/rosout for ROS-dependent packages.
CATEGORIES=	sysutils
LICENSE=	BSD3CLAUSE
WWW=	https://github.com/ros/console_bridge
USES=	cmake:outsource
USE_GITHUB=	yes
GH_ACCOUNT=	ros
GH_PROJECT=	console_bridge
GH_TAGNAME=	0.4.0

.include <bsd.port.mk>
