# $FreeBSD$

PORTNAME=	ros-console_bridge
DISTVERSION=	0.4.0
CATEGORIES=	sysutils

MAINTAINER=	trentonw@ifi.uio.no
COMMENT=	ROS-independent logging that pipes into ROS packages

LICENSE=	BSD3CLAUSE

WWW=	https://github.com/ros/console_bridge
USES=	cmake:outsource
USE_GITHUB=	yes
GH_ACCOUNT=	ros
GH_PROJECT=	console_bridge
GH_TAGNAME=	0.4.0

.include <bsd.port.mk>
