# $FreeBSD$

PORTNAME=	ros-urdfdom_headers
DISTVERSION=	1.0.0
CATEGORIES=	devel

MAINTAINER=	trueos@norwegianrockcat.com
COMMENT=	Headers for URDF parsers

LICENSE=	BSD3CLAUSE

WWW=	http://ros.org/wiki/urdf
USES=	cmake
USE_GITHUB=	yes
GH_ACCOUNT=	ros
GH_PROJECT=	urdfdom_headers
GH_TAGNAME=	1.0.0

.include <bsd.port.mk>
